'use strict';

export const SET_CIRCUIT = 'SET_CIRCUIT_STATE';
export const SET_CIRCUIT_SUCCESS = 'SET_CIRCUIT_SUCCESS';
export const SET_CIRCUIT_FAIL = 'SET_CIRCUIT_FAIL';

export const GET_HEALTH = 'GET_HEALTH';
export const GET_HEALTH_SUCCESS = 'GET_HEALTH_SUCCESS';
export const GET_HEALTH_FAIL = 'GET_HEALTH_FAIL';

export const SET_CONTROL_CLASS_NAME = 'SET_CONTROL_CLASS_NAME';
export const SET_SERVICE_CLASS_NAME = 'SET_SERVICE_CLASS_NAME';
export const SET_SERVICE_LIST = 'SET_SERVICE_LIST';